### ISSUE TITLE
Behaviour on throw differs from geth

### ISSUE THREAD

**Issue by area** [ethereumjs/testrpc#39]
`testrpc` and `geth` behave in very different ways when encountering a `throw` in a contract, which is making writing tests that check invalid calls to contracts are correctly prevented in `truffle` difficult.

`testrpc` throws an error:

```
[Error: Error: VM Exception while executing transaction: invalid JUMP
    at /Users/user/.node/lib/node_modules/ethereumjs-testrpc/lib/blockchain.js:471:18
    at Object.async.eachSeries (/Users/user/.node/lib/node_modules/ethereumjs-testrpc/node_modules/async-eventemitter/node_modules/async/lib/async.js:130:20)
    at VM.AsyncEventEmitter.emit (/Users/user/.node/lib/node_modules/ethereumjs-testrpc/node_modules/async-eventemitter/lib/AsyncEventEmitter.js:42:9)
    at afterBlock (/Users/user/.node/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-vm/lib/runBlock.js:55:10)
    at /Users/user/.node/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-vm/lib/runBlock.js:179:9
    at /Users/user/.node/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-vm/lib/cache.js:137:7
    at /Users/user/.node/lib/node_modules/ethereumjs-testrpc/node_modules/async/lib/async.js:52:16
    at iterate (/Users/user/.node/lib/node_modules/ethereumjs-testrpc/node_modules/async/lib/async.js:260:24)
    at Object.async.forEachOfSeries.async.eachOfSeries (/Users/user/.node/lib/node_modules/ethereumjs-testrpc/node_modules/async/lib/async.js:281:9)
    at Object.async.forEachSeries.async.eachSeries (/Users/user/.node/lib/node_modules/ethereumjs-testrpc/node_modules/async/lib/async.js:214:22)]
```

`throw` is indeed meant to create an invalid jump error, but it should still create a transaction without erroring as `geth` does. From https://www.ethereum.org/token :

> 'throw' will cancel all contract execution, revert any changes that transaction could have made and the sender will lose all ether he sent on gas. 

In order to get tests to pass in both `testrpc` and `geth`, currently a special `catch` in the promise chain is required deal with the possibility the tests might be running on `testrpc`. I does seem to be true that `testrpc` correctly spends all the gas bought by the key making the transaction - it's just throwing the VM error all the way up.

I can't figure out what the lines https://github.com/ethereumjs/testrpc/blob/master/lib/blockchain.js#L469-L473 are meant to be doing. I don't think an error should be thrown here, ultimately - a VM exception still produces a 'valid' transaction, right? Removing these lines gives me the behaviour I'd expect to see, I think, but there are no tests for 'invalid' transactions, so I'm certainly hesitant to do anything about it without properly understanding what's going on. I feel like I'm way out of my depth here...(!)

**Comment by tcoulter** [comment]
Unfortunately there's nothing we can do about this. This issue has been discussed before. It revolves around these two points:

1. In the VM bytecode, there's no difference between a throw and an invalid jump, and so there's no way for the TestRPC to distinguish between the two.
2. In order for the TestRPC to be valuable, it should throw errors like invalid jump when your contracts fail, so you know exactly which transaction caused the error (and you can debug it).

Since fixing (1) would require not having the value of (2), we've decided if you want your tests to run correctly with the TestRPC, you must implement the special catch you mentioned.

> I can't figure out what the lines https://github.com/ethereumjs/testrpc/blob/master/lib/blockchain.js#L469-L473 are meant to be doing.

This code ensures that if your contract code fails for some reason, like invalid jump (for instance, you called code at an address that doesn't exist or doesn't have code in it) that you know immediately so you know you're coding or interacting with your contracts incorrectly. It's valuable behavior especially to those new to writing contracts. We recommend you implement your special catch instead in the case where your contracts encounter a throw.

**Comment by area** [comment]
Okay, this all makes sense, thanks for taking the time to explain so thoroughly. I have naively been assuming until this point that the ultimate goal of `testrpc` was to be a fast `geth` for development purposes, and respond in exactly the same ways apart from the time needed to 'mine' a transaction. Sorry for the confusion.

**Comment by tcoulter** [comment]
Ya, that's mostly the case. There's a less loudly stated goal of making it easier to develop: since geth hides actual errors (vs. throws), it becomes very hard to know which transaction caused the issue in a string of transactions.

Completely understand the confusion though. If the bytecode had an opcode for throw, we'd be able to detect it and respond accordingly.
